// <auto-generated />
namespace Project_AutoSuggestion_E_AppointmentApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AppContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201408280524296_AppContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
